name: TerozaxCore
author: Teroaz
version: 1.0.0
api-version : "1.13"
description: Plugin me permettant l'apprentissage de Spigot & du Kotlin
main: main.Loader

commands:
  heal:
    description: Se soigner ou soigner un joueur
    permission: terozax.heal
  broadcast:
    description: Diffuser un message à tous les joueurs
    permission: terozax.broadcast
    aliases : ["bc"]
  players:
    description: Lister les joueurs connectés
    permission: terozax.players
  invsee:
    description: Apercevoir l'inventaire d'un joueur
    permission: terozax.invsee